"""add_multi_tier_referrals

Revision ID: 0c58292a9537
Revises: 5dc8dfce9fd3
Create Date: 2026-07-24 10:46:25.057759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c58292a9537'
down_revision: Union[str, None] = '5dc8dfce9fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('bank_statement_transactions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('ix_branches_code'), 'branches', type_='unique')
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.drop_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', type_='unique')
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], unique=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_employees_employee_number'), 'employees', type_='unique')
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.alter_column('group_meetings', 'minutes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', type_='unique')
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', type_='unique')
    op.create_index(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], unique=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('members', 'physical_address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('members', 'dormancy_notified_stage',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('ix_members_member_number'), 'members', type_='unique')
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.drop_constraint(op.f('ix_members_national_id'), 'members', type_='unique')
    op.create_index(op.f('ix_members_national_id'), 'members', ['national_id'], unique=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payslips', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PAID', name='payslippaymentstatus'),
               existing_nullable=False)
    op.alter_column('referrals', 'referrer_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('referrals', 'referred_user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('referrals', 'tier',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('referrals', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'COMPLETED', 'INVALID', 'INVITED', 'REGISTERED', 'COMMISSION_PAID', 'EXPIRED', name='referralstatus'),
               existing_nullable=False)
    op.alter_column('referrals', 'referral_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('referrals', 'referrer_member_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('referrals', 'referred_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('referrals', 'referred_contact',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('referrals', 'channel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EMAIL', 'SMS', 'PUSH', name='notificationchannel'),
               nullable=True)
    op.drop_constraint(op.f('ix_referrals_referral_code'), 'referrals', type_='unique')
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True)
    op.create_unique_constraint('uq_referral_user_tier', 'referrals', ['referred_user_id', 'tier'])
    op.create_foreign_key(None, 'referrals', 'users', ['referrer_id'], ['id'])
    op.create_foreign_key(None, 'referrals', 'users', ['referred_user_id'], ['id'])
    op.alter_column('risk_flags', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', type_='unique')
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.drop_constraint(op.f('ix_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('ix_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.create_unique_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint('uq_referral_user_tier', 'referrals', type_='unique')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.create_unique_constraint(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('referrals', 'channel',
               existing_type=sa.Enum('EMAIL', 'SMS', 'PUSH', name='notificationchannel'),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('referrals', 'referred_contact',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('referrals', 'referred_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('referrals', 'referrer_member_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('referrals', 'referral_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('referrals', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'INVALID', 'INVITED', 'REGISTERED', 'COMMISSION_PAID', 'EXPIRED', name='referralstatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('referrals', 'tier',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('referrals', 'referred_user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('referrals', 'referrer_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('payslips', 'payment_status',
               existing_type=sa.Enum('PENDING', 'PAID', name='payslippaymentstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_national_id'), 'members', ['national_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_member_number'), 'members', ['member_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('members', 'dormancy_notified_stage',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('members', 'physical_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_applications_loan_number'), table_name='loan_applications')
    op.create_unique_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.create_unique_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('group_meetings', 'minutes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.create_unique_constraint(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_unique_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.create_unique_constraint(op.f('ix_branches_code'), 'branches', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('bank_statement_transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
