"""step2

Revision ID: 19e650e89834
Revises: b3e3383f827d
Create Date: 2026-07-07 23:57:14.196873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e650e89834'
down_revision: Union[str, None] = 'b3e3383f827d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS "ix_chart_of_accounts_code" CASCADE')
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], unique=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS "ix_journal_entries_entry_number" CASCADE')
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS "ix_loan_applications_loan_number" CASCADE')
    op.create_index(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], unique=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('members', 'physical_address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS "ix_members_member_number" CASCADE')
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.execute('DROP INDEX IF EXISTS "ix_members_national_id" CASCADE')
    op.create_index(op.f('ix_members_national_id'), 'members', ['national_id'], unique=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS "ix_savings_accounts_account_number" CASCADE')
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS "ix_users_email" CASCADE')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('ix_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.create_unique_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_national_id'), 'members', ['national_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_member_number'), 'members', ['member_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('members', 'physical_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_applications_loan_number'), table_name='loan_applications')
    op.create_unique_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.create_unique_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_unique_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
