"""step6

Revision ID: 5d599c1583ad
Revises: f1ec9a0d127e
Create Date: 2026-07-20 03:29:45.342638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d599c1583ad'
down_revision: Union[str, None] = 'f1ec9a0d127e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', type_='unique', if_exists=True)
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], unique=True, if_not_exists=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_employees_employee_number'), 'employees', type_='unique', if_exists=True)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True, if_not_exists=True)
    op.add_column('gl_settings', sa.Column('interest_expense_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('gl_settings', sa.Column('salaries_expense_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('gl_settings', sa.Column('nssf_expense_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('gl_settings', sa.Column('paye_payable_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('gl_settings', sa.Column('nssf_payable_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['nssf_expense_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['salaries_expense_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['interest_expense_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['nssf_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['paye_payable_account_id'], ['id'])
    op.add_column('group_loan_guarantees', sa.Column('approved_by_user_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('group_loan_guarantees', sa.Column('approved_at', sa.DateTime(), nullable=True), if_not_exists=True)
    op.add_column('group_loan_guarantees', sa.Column('created_at', sa.DateTime(), nullable=False), if_not_exists=True)
    op.create_foreign_key(None, 'group_loan_guarantees', 'users', ['approved_by_user_id'], ['id'])
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', type_='unique', if_exists=True)
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True, if_not_exists=True)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', type_='unique', if_exists=True)
    op.create_index(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], unique=True, if_not_exists=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('members', 'physical_address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_members_member_number'), 'members', type_='unique', if_exists=True)
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True, if_not_exists=True)
    op.drop_constraint(op.f('ix_members_national_id'), 'members', type_='unique', if_exists=True)
    op.create_index(op.f('ix_members_national_id'), 'members', ['national_id'], unique=True, if_not_exists=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payslips', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('referrals', 'channel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('referrals', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint(op.f('ix_referrals_referral_code'), 'referrals', type_='unique', if_exists=True)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True, if_not_exists=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('savings_accounts', sa.Column('last_interest_posted_at', sa.DateTime(), nullable=True), if_not_exists=True)
    op.drop_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', type_='unique', if_exists=True)
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True, if_not_exists=True)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_users_email'), 'users', type_='unique', if_exists=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('ix_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.create_unique_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('savings_accounts', 'last_interest_posted_at')
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.create_unique_constraint(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('referrals', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('referrals', 'channel',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payslips', 'payment_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_national_id'), 'members', ['national_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_member_number'), 'members', ['member_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('members', 'physical_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_applications_loan_number'), table_name='loan_applications')
    op.create_unique_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.create_unique_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'group_loan_guarantees', type_='foreignkey')
    op.drop_column('group_loan_guarantees', 'created_at')
    op.drop_column('group_loan_guarantees', 'approved_at')
    op.drop_column('group_loan_guarantees', 'approved_by_user_id')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_column('gl_settings', 'nssf_payable_account_id')
    op.drop_column('gl_settings', 'paye_payable_account_id')
    op.drop_column('gl_settings', 'nssf_expense_account_id')
    op.drop_column('gl_settings', 'salaries_expense_account_id')
    op.drop_column('gl_settings', 'interest_expense_account_id')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.create_unique_constraint(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_unique_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
