"""add_dormancy_stage_bank_rec_and_group_meetings

Revision ID: 5dc8dfce9fd3
Revises: e37a4c5483af
Create Date: 2026-07-23 21:33:50.478380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc8dfce9fd3'
down_revision: Union[str, None] = 'e37a4c5483af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_meetings',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['member_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_attendance',
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['group_meetings.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_statements',
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_statement_transactions',
    sa.Column('statement_id', sa.String(length=36), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('matched_journal_entry_id', sa.String(length=36), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['matched_journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_branches_code'), 'branches', type_='unique')
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.drop_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', type_='unique')
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], unique=True)
    op.add_column('collaterals', sa.Column('is_released', sa.Boolean(), nullable=False))
    op.add_column('collaterals', sa.Column('released_at', sa.DateTime(), nullable=True))
    op.alter_column('collaterals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_employees_employee_number'), 'employees', type_='unique')
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', type_='unique')
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', type_='unique')
    op.create_index(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], unique=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('members', sa.Column('dormancy_notified_stage', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('members', 'physical_address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_members_member_number'), 'members', type_='unique')
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.drop_constraint(op.f('ix_members_national_id'), 'members', type_='unique')
    op.create_index(op.f('ix_members_national_id'), 'members', ['national_id'], unique=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payslips', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PAID', name='payslippaymentstatus'),
               existing_nullable=False)
    op.alter_column('referrals', 'channel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EMAIL', 'SMS', 'PUSH', name='notificationchannel'),
               existing_nullable=False)
    op.alter_column('referrals', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('INVITED', 'REGISTERED', 'COMMISSION_PAID', 'EXPIRED', name='referralstatus'),
               existing_nullable=False)
    op.drop_constraint(op.f('ix_referrals_referral_code'), 'referrals', type_='unique')
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', type_='unique')
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('ix_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.create_unique_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.create_unique_constraint(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('referrals', 'status',
               existing_type=sa.Enum('INVITED', 'REGISTERED', 'COMMISSION_PAID', 'EXPIRED', name='referralstatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('referrals', 'channel',
               existing_type=sa.Enum('EMAIL', 'SMS', 'PUSH', name='notificationchannel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payslips', 'payment_status',
               existing_type=sa.Enum('PENDING', 'PAID', name='payslippaymentstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_national_id'), 'members', ['national_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_member_number'), 'members', ['member_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('members', 'physical_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('members', 'dormancy_notified_stage')
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_applications_loan_number'), table_name='loan_applications')
    op.create_unique_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.create_unique_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.create_unique_constraint(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('collaterals', 'released_at')
    op.drop_column('collaterals', 'is_released')
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_unique_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.create_unique_constraint(op.f('ix_branches_code'), 'branches', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('bank_statement_transactions')
    op.drop_table('bank_statements')
    op.drop_table('group_attendance')
    op.drop_table('group_meetings')
    # ### end Alembic commands ###
