"""step4

Revision ID: 8f1022f475a3
Revises: c22d1405cfdb
Create Date: 2026-07-20 02:31:25.446858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1022f475a3'
down_revision: Union[str, None] = 'c22d1405cfdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('referral_commission_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('employees',
    sa.Column('employee_number', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employment_date', sa.Date(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tin', sa.String(length=30), nullable=True),
    sa.Column('nssf_number', sa.String(length=30), nullable=True),
    sa.Column('mobile_money_number', sa.String(length=20), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True, if_not_exists=True)
    op.create_table('payroll_runs',
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSED', name='payrollrunstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('total_gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_paye', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_nssf_employee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_nssf_employer', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_loan_deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('referrals',
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referrer_member_id', sa.String(length=36), nullable=False),
    sa.Column('referred_name', sa.String(length=150), nullable=False),
    sa.Column('referred_contact', sa.String(length=150), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', name='notificationchannel', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'REGISTERED', 'COMMISSION_PAID', 'EXPIRED', name='referralstatus'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('registered_member_id', sa.String(length=36), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission_paid_savings_account_id', sa.String(length=36), nullable=True),
    sa.Column('commission_paid_at', sa.DateTime(), nullable=True),
    sa.Column('commission_paid_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commission_paid_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['commission_paid_savings_account_id'], ['savings_accounts.id'], ),
    sa.ForeignKeyConstraint(['referrer_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['registered_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True, if_not_exists=True)
    op.create_table('payslips',
    sa.Column('payroll_run_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paye_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nssf_employee_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nssf_employer_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('loan_deduction_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', name='payslippaymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', type_='unique')
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], unique=True, if_not_exists=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('gl_settings', sa.Column('interest_expense_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('gl_settings', sa.Column('salaries_expense_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('gl_settings', sa.Column('nssf_expense_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('gl_settings', sa.Column('paye_payable_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('gl_settings', sa.Column('nssf_payable_account_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['nssf_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['paye_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['salaries_expense_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['nssf_expense_account_id'], ['id'])
    op.create_foreign_key(None, 'gl_settings', 'chart_of_accounts', ['interest_expense_account_id'], ['id'])
    op.add_column('group_loan_guarantees', sa.Column('approved_by_user_id', sa.String(length=36), nullable=True), if_not_exists=True)
    op.add_column('group_loan_guarantees', sa.Column('approved_at', sa.DateTime(), nullable=True), if_not_exists=True)
    op.add_column('group_loan_guarantees', sa.Column('created_at', sa.DateTime(), nullable=False), if_not_exists=True)
    op.create_foreign_key(None, 'group_loan_guarantees', 'users', ['approved_by_user_id'], ['id'])
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', type_='unique')
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True, if_not_exists=True)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', type_='unique')
    op.create_index(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], unique=True, if_not_exists=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('members', 'physical_address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_members_member_number'), 'members', type_='unique')
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True, if_not_exists=True)
    op.drop_constraint(op.f('ix_members_national_id'), 'members', type_='unique')
    op.create_index(op.f('ix_members_national_id'), 'members', ['national_id'], unique=True, if_not_exists=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('savings_accounts', sa.Column('last_interest_posted_at', sa.DateTime(), nullable=True), if_not_exists=True)
    op.drop_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', type_='unique')
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True, if_not_exists=True)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('ix_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.create_unique_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('savings_accounts', 'last_interest_posted_at')
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_national_id'), 'members', ['national_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_member_number'), 'members', ['member_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('members', 'physical_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_applications_loan_number'), table_name='loan_applications')
    op.create_unique_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.create_unique_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'group_loan_guarantees', type_='foreignkey')
    op.drop_column('group_loan_guarantees', 'created_at')
    op.drop_column('group_loan_guarantees', 'approved_at')
    op.drop_column('group_loan_guarantees', 'approved_by_user_id')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_constraint(None, 'gl_settings', type_='foreignkey')
    op.drop_column('gl_settings', 'nssf_payable_account_id')
    op.drop_column('gl_settings', 'paye_payable_account_id')
    op.drop_column('gl_settings', 'nssf_expense_account_id')
    op.drop_column('gl_settings', 'salaries_expense_account_id')
    op.drop_column('gl_settings', 'interest_expense_account_id')
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_unique_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('payslips')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
