"""initial

Revision ID: b3e3383f827d
Revises: 
Create Date: 2026-07-03 10:45:18.503451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e3383f827d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], unique=True)
    op.create_table('dividend_declarations',
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('rate_per_share', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('declared_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_products',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('interest_rate_annual', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('max_repayment_months', sa.Integer(), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('penalty_rate_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('requires_guarantors', sa.Boolean(), nullable=False),
    sa.Column('min_guarantors', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_groups',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_products',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('interest_rate_annual', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('interest_frequency', sa.String(length=20), nullable=False),
    sa.Column('minimum_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cooling_period_days', sa.Integer(), nullable=False),
    sa.Column('withdrawal_penalty_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_products',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nominal_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_shares_per_member', sa.Integer(), nullable=False),
    sa.Column('max_shares_per_member', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('member_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('employer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DORMANT', 'SUSPENDED', 'EXITED', name='memberstatus'), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.create_index(op.f('ix_members_national_id'), 'members', ['national_id'], unique=True)
    op.create_table('dividend_payouts',
    sa.Column('declaration_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('option', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['declaration_id'], ['dividend_declarations.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_contributions',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['member_groups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_memberships',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('CHAIR', 'SECRETARY', 'TREASURER', 'MEMBER', name='grouprole'), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['member_groups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('next_of_kin',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_accounts',
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('last_transaction_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['savings_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True)
    op.create_table('share_holdings',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('number_of_shares', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['share_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trusted_contacts',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'LOAN_OFFICER', 'ACCOUNTANT', 'HR_OFFICER', 'TELLER', 'MEMBER', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_reports',
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('generated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('file_reference', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('entry_number', sa.String(length=30), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('source_module', sa.String(length=50), nullable=True),
    sa.Column('source_reference_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', name='journalentrystatus'), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True)
    op.create_table('loan_applications',
    sa.Column('loan_number', sa.String(length=30), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_approved', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('repayment_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'DISBURSED', 'ACTIVE', 'CLOSED', 'DEFAULTED', 'RESCHEDULED', name='loanstatus'), nullable=False),
    sa.Column('is_non_member_applicant', sa.Boolean(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('disbursement_channel', sa.Enum('SAVINGS_ACCOUNT', 'MOBILE_MONEY', 'BANK', 'CASH', name='disbursementchannel'), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('disbursement_savings_account_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disbursement_savings_account_id'], ['savings_accounts.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], unique=True)
    op.create_table('notifications',
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', name='notificationchannel'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_files',
    sa.Column('employer_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('file_reference', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_transactions',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('txn_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'INTEREST_POSTING', 'TRANSFER_IN', 'TRANSFER_OUT', 'PENALTY', name='savingstxntype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('performed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['savings_accounts.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_transactions',
    sa.Column('holding_id', sa.String(length=36), nullable=False),
    sa.Column('txn_type', sa.Enum('SUBSCRIPTION', 'TRANSFER', 'REDEMPTION', 'DIVIDEND', name='sharetxntype'), nullable=False),
    sa.Column('number_of_shares', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('counterparty_member_id', sa.String(length=36), nullable=True),
    sa.Column('board_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['holding_id'], ['share_holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaterals',
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('collateral_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('document_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_loan_guarantees',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('amount_guaranteed', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['member_groups.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guarantors',
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('guarantor_member_id', sa.String(length=36), nullable=False),
    sa.Column('amount_guaranteed', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'RELEASED', name='guarantorstatus'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guarantor_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_lines',
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_repayment_schedules',
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('penalty_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_transactions',
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('txn_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('performed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_deductions',
    sa.Column('payroll_file_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=True),
    sa.Column('savings_account_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'RECONCILED', 'EXCEPTION', name='deductionstatus'), nullable=False),
    sa.Column('exception_reason', sa.Text(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['payroll_file_id'], ['payroll_files.id'], ),
    sa.ForeignKeyConstraint(['savings_account_id'], ['savings_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_flags',
    sa.Column('flag_type', sa.Enum('AML_SUSPICIOUS_DEPOSIT', 'DUPLICATE_ID', 'MULTIPLE_LOANS', 'GHOST_MEMBER', 'LOAN_DEFAULT_RISK', name='riskflagtype'), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('loan_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'ESCALATED', name='riskflagstatus'), nullable=False),
    sa.Column('resolved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_flags')
    op.drop_table('payroll_deductions')
    op.drop_table('loan_transactions')
    op.drop_table('loan_repayment_schedules')
    op.drop_table('journal_lines')
    op.drop_table('guarantors')
    op.drop_table('group_loan_guarantees')
    op.drop_table('collaterals')
    op.drop_table('share_transactions')
    op.drop_table('savings_transactions')
    op.drop_table('payroll_files')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_loan_applications_loan_number'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('compliance_reports')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trusted_contacts')
    op.drop_table('share_holdings')
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.drop_table('savings_accounts')
    op.drop_table('next_of_kin')
    op.drop_table('group_memberships')
    op.drop_table('group_contributions')
    op.drop_table('dividend_payouts')
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.drop_table('members')
    op.drop_table('share_products')
    op.drop_table('savings_products')
    op.drop_table('member_groups')
    op.drop_table('loan_products')
    op.drop_table('employers')
    op.drop_table('dividend_declarations')
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
