"""step3

Revision ID: c22d1405cfdb
Revises: 19e650e89834
Create Date: 2026-07-10 08:47:09.355493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22d1405cfdb'
down_revision: Union[str, None] = '19e650e89834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], unique=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_applications_loan_number'), table_name='loan_applications')
    op.create_index(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], unique=True)
    op.add_column('loan_products', sa.Column('gl_asset_account_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['gl_asset_account_id'], ['id'])
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('members', 'physical_address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.create_index(op.f('ix_members_national_id'), 'members', ['national_id'], unique=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True)
    op.add_column('savings_products', sa.Column('gl_liability_account_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'savings_products', 'chart_of_accounts', ['gl_liability_account_id'], ['id'])
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('ix_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('savings_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'savings_products', type_='foreignkey')
    op.drop_column('savings_products', 'gl_liability_account_id')
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.create_unique_constraint(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('risk_flags', 'resolution_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('risk_flags', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('payroll_deductions', 'exception_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('mobile_money_transactions', 'raw_last_callback',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('mobile_money_transactions', 'failure_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_national_id'), 'members', ['national_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_member_number'), 'members', ['member_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('members', 'physical_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('loan_transactions', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_column('loan_products', 'gl_asset_account_id')
    op.drop_index(op.f('ix_loan_applications_loan_number'), table_name='loan_applications')
    op.create_unique_constraint(op.f('ix_loan_applications_loan_number'), 'loan_applications', ['loan_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.create_unique_constraint(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('journal_entries', 'narrative',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('compliance_reports', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('collaterals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_unique_constraint(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
